.docker:
  stage: prepare
  tags: [$DOCKER_SHELL_TAG]
  variables: { DOCKER_BUILDKIT: 1 }
  script: ["docker build $DOCKER_OPTS -t $DOCKER_IMAGE:$DOCKER_TAG --build-arg OS_DISTRO=$OS_DISTRO --build-arg OS_RELEASE=$OS_RELEASE -f docker/Dockerfile.gitlab-ci ."]

docker [Oracle Linux 8]:
  extends: .docker
  variables:
    OS_DISTRO: "oraclelinux"
    OS_RELEASE: "8"
    DOCKER_TAG: "ol8"

docker [Oracle Linux 9]:
  extends: .docker
  variables:
    OS_DISTRO: "oraclelinux"
    OS_RELEASE: "9"
    DOCKER_TAG: "ol9"

docker [Rocky Linux 9]:
  extends: .docker
  variables:
    OS_DISTRO: "rockylinux"
    OS_RELEASE: "9"
    DOCKER_TAG: "rl9"

docker-rebuild [Oracle Linux 8]:
  extends: "docker [Oracle Linux 8]"
  variables: { DOCKER_OPTS: --no-cache }
  when: manual

docker-rebuild [Oracle Linux 9]:
  extends: "docker [Oracle Linux 9]"
  variables: { DOCKER_OPTS: --no-cache }
  when: manual

docker-rebuild [Rocky Linux 9]:
  extends: "docker [Rocky Linux 9]"
  variables: { DOCKER_OPTS: --no-cache }
  when: manual
